version: '3.8'

networks:
  default:
    name: 'inventory_system'

volumes:
  data:
    driver: local
  config:
    driver: local
  cache:
    driver: local

services:
  db:
    container_name: 'inventory_system_db'
    image: mysql:8.0.30
    platform: linux/x86_64
    restart: always
    ports:
      - '33306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_systems
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
      TZ: Asia/Seoul
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql.conf.d
  redis:
    container_name: 'inventory_system_redis'
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
